/** @type {import('tailwindcss').Config} */
module.exports = {
    'c0': {
        'soft': 'rgb(var(--c0-soft) / <alpha-value>)',
        'mist': 'rgb(var(--c0-mist) / <alpha-value>)',
        'dawn': 'rgb(var(--c0-dawn) / <alpha-value>)',
        'regular': 'rgb(var(--c0-regular) / <alpha-value>)',
        'dust': 'rgb(var(--c0-dust) / <alpha-value>)',
        'dark': 'rgb(var(--c0-dark) / <alpha-value>)',
        DEFAULT: 'rgb(var(--c0) / <alpha-value>)',
    },
    'c1': {
        'soft': 'rgb(var(--c1-soft) / <alpha-value>)',
        'mist': 'rgb(var(--c1-mist) / <alpha-value>)',
        'dawn': 'rgb(var(--c1-dawn) / <alpha-value>)',
        'regular': 'rgb(var(--c1-regular) / <alpha-value>)',
        'dust': 'rgb(var(--c1-dust) / <alpha-value>)',
        'dark': 'rgb(var(--c1-dark) / <alpha-value>)',
        DEFAULT: 'rgb(var(--c1) / <alpha-value>)',
    },
    'c2': {
        'soft': 'rgb(var(--c2-soft) / <alpha-value>)',
        'mist': 'rgb(var(--c2-mist) / <alpha-value>)',
        'dawn': 'rgb(var(--c2-dawn) / <alpha-value>)',
        'regular': 'rgb(var(--c2-regular) / <alpha-value>)',
        'dust': 'rgb(var(--c2-dust) / <alpha-value>)',
        'dark': 'rgb(var(--c2-dark) / <alpha-value>)',
        DEFAULT: 'rgb(var(--c2) / <alpha-value>)',
    },
    '3': {
        'soft': 'rgb(var(--3-soft) / <alpha-value>)',
        'mist': 'rgb(var(--3-mist) / <alpha-value>)',
        'dawn': 'rgb(var(--3-dawn) / <alpha-value>)',
        'regular': 'rgb(var(--3-regular) / <alpha-value>)',
        'dust': 'rgb(var(--3-dust) / <alpha-value>)',
        'dark': 'rgb(var(--3-dark) / <alpha-value>)',
        DEFAULT: 'rgb(var(--3) / <alpha-value>)',
    },
    'c4': {
        'soft': 'rgb(var(--c4-soft) / <alpha-value>)',
        'mist': 'rgb(var(--c4-mist) / <alpha-value>)',
        'dawn': 'rgb(var(--c4-dawn) / <alpha-value>)',
        'regular': 'rgb(var(--c4-regular) / <alpha-value>)',
        'dust': 'rgb(var(--c4-dust) / <alpha-value>)',
        'dark': 'rgb(var(--c4-dark) / <alpha-value>)',
        DEFAULT: 'rgb(var(--c4) / <alpha-value>)',
    },
}