/** @type {import('tailwindcss').Config} */
module.exports = {
    'gray': {
        '100': 'rgb(var(--gray-100) / <alpha-value>)',
        '200': 'rgb(var(--gray-200) / <alpha-value>)',
        '300': 'rgb(var(--gray-300) / <alpha-value>)',
        '400': 'rgb(var(--gray-400) / <alpha-value>)',
        '500': 'rgb(var(--gray-500) / <alpha-value>)',
        '600': 'rgb(var(--gray-600) / <alpha-value>)',
        DEFAULT: 'rgb(var(--gray) / <alpha-value>)',
    },
    'yellow': {
        '100': 'rgb(var(--yellow-100) / <alpha-value>)',
        '200': 'rgb(var(--yellow-200) / <alpha-value>)',
        '300': 'rgb(var(--yellow-300) / <alpha-value>)',
        '400': 'rgb(var(--yellow-400) / <alpha-value>)',
        '500': 'rgb(var(--yellow-500) / <alpha-value>)',
        '600': 'rgb(var(--yellow-600) / <alpha-value>)',
        DEFAULT: 'rgb(var(--yellow) / <alpha-value>)',
    },
    'pink': {
        '100': 'rgb(var(--pink-100) / <alpha-value>)',
        '200': 'rgb(var(--pink-200) / <alpha-value>)',
        '300': 'rgb(var(--pink-300) / <alpha-value>)',
        '400': 'rgb(var(--pink-400) / <alpha-value>)',
        '500': 'rgb(var(--pink-500) / <alpha-value>)',
        '600': 'rgb(var(--pink-600) / <alpha-value>)',
        DEFAULT: 'rgb(var(--pink) / <alpha-value>)',
    },
    'green': {
        '100': 'rgb(var(--green-100) / <alpha-value>)',
        '200': 'rgb(var(--green-200) / <alpha-value>)',
        '300': 'rgb(var(--green-300) / <alpha-value>)',
        '400': 'rgb(var(--green-400) / <alpha-value>)',
        '500': 'rgb(var(--green-500) / <alpha-value>)',
        '600': 'rgb(var(--green-600) / <alpha-value>)',
        DEFAULT: 'rgb(var(--green) / <alpha-value>)',
    },
    'blue': {
        '100': 'rgb(var(--blue-100) / <alpha-value>)',
        '200': 'rgb(var(--blue-200) / <alpha-value>)',
        '300': 'rgb(var(--blue-300) / <alpha-value>)',
        '400': 'rgb(var(--blue-400) / <alpha-value>)',
        '500': 'rgb(var(--blue-500) / <alpha-value>)',
        '600': 'rgb(var(--blue-600) / <alpha-value>)',
        DEFAULT: 'rgb(var(--blue) / <alpha-value>)',
    },
}